version: 2.1

orbs:
  slack: circleci/slack@4.12.5  # Slack Orb oficial

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

jobs:
  install-deps:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Crear entorno virtual e instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - .

  test:
    executor: python-executor
    parallelism: 2  # Ejecutar pruebas en paralelo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Ejecutar pruebas con Pytest en paralelo
          command: |
            . venv/bin/activate
            pytest tests/ --maxfail=1 --dist=loadfile --tx 2*popen

  notify_success:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

  notify_failure:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  test_and_notify:
    jobs:
      - install-deps
      - test:
          requires:
            - install-deps
      - notify_success:
          requires:
            - test
          filters:
            branches:
              only: main
      - notify_failure:
          requires:
            - test
          filters:
            branches:
              only: main
