version: 2.1

orbs:
  slack: circleci/slack@4.12.5

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: pip install -r requirements.txt

  run-tests:
    executor: python-executor
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Instalar dependencias para pruebas
          command: pip install -r requirements.txt
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            TESTFILES=$(circleci tests split --split-by=name)
            pytest $TESTFILES
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Simulación de despliegue
          command: echo "Desplegando la app..."
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - run-tests
          filters:
            branches:
              only: main
