version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

jobs:
  install-deps:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install -r requirements.txt
            pip install pytest-xdist

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install -r requirements.txt
            pip install pytest-xdist
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            set +e
            PYTHONPATH=. pytest -n 2
            TEST_RESULT=$?
            if [ $TEST_RESULT -eq 0 ]; then
              echo "✅ ¡El pipeline finalizó con éxito!"
            else
              echo "❌ El pipeline falló. Revisa los errores."
              exit $TEST_RESULT
            fi

workflows:
  test_and_notify:
    jobs:
      - install-deps
      - run-tests:
          requires:
            - install-deps
