version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

jobs:
  install-deps:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            . venv/bin/activate
            PYTHONPATH=. pytest -n 2

  notify-success:
    executor: python-executor
    steps:
      - run: echo "✅ Build exitosa. Notificación enviada (simulada)."

  notify-failure:
    executor: python-executor
    steps:
      - run: echo "❌ Build fallida. Notificación enviada (simulada)."

workflows:
  version: 2
  test_and_notify:
    jobs:
      - install-deps
      - run-tests:
          requires:
            - install-deps
          filters:
            branches:
              only: main
      - notify-success:
          requires:
            - run-tests
          filters:
            branches:
              only: main
          when: on_success
      - notify-failure:
          requires:
            - run-tests
          filters:
            branches:
              only: main
          when: on_fail
