version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

jobs:
  install-deps:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install -r requirements.txt
            pip install pytest-xdist

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install -r requirements.txt
            pip install pytest-xdist
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            PYTHONPATH=. pytest -n 2

  notify-success:
    executor: python-executor
    steps:
      - run: echo "✅ ¡El pipeline finalizó con éxito!"

  notify-failure:
    executor: python-executor
    steps:
      - run: echo "❌ El pipeline falló. Revisa los errores."

workflows:
  test_and_notify:
    jobs:
      - install-deps
      - run-tests:
          requires:
            - install-deps
      - notify-success:
          requires:
            - run-tests
          filters:
            branches:
              only: main
      - notify-failure:
          requires:
            - run-tests
          filters:
            branches:
              only: main
          when: on_fail
